language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

env:
  - CAKE_VERSION=2.5.5

git:
  submodules: false

matrix:
  fast-finish: true
  include:
    - php: 5.4
      env: CAKE_VERSION=2.4.10
    - php: 5.4
      env: PHPCS=1

before_install:
  - sh -c "if [ '$PHPCS' != '1' ]; then git submodule update --init --recursive; fi"

before_script:
  - sh -c "if [ '$PHPCS' != '1' ]; then
      git clone https://github.com/cakephp/cakephp.git ../cakephp;
      cd ../cakephp;
      git checkout $CAKE_VERSION;
      cp -R ../MustacheCake app/Plugin/MustacheCake;
      chmod -R 777 app/tmp;
      composer global require 'phpunit/phpunit=3.7.33';
      ln -s ~/.composer/vendor/phpunit/phpunit/PHPUnit vendors/PHPUnit;
      fi"
  - sh -c "if [ '$PHPCS' = '1' ]; then
      pear channel-discover pear.cakephp.org;
      pear install --alldeps cakephp/CakePHP_CodeSniffer;
      phpenv rehash;
      fi"

script:
  - sh -c "if [ '$PHPCS' != '1' ]; then
      cd ../cakephp/app;
      ./Console/cake test MustacheCake AllTests --stderr;
      fi"
  - sh -c "if [ '$PHPCS' = '1' ]; then phpcs -p --extensions=php --standard=CakePHP --ignore=Vendor .; fi"

notifications:
  email: false
